title: Integration Tools
description: Breaking the concept of Integrations are just mapping of data structures.<br/>Integration Tools aim towards providing building blocks, patterns and a place to enjoy building and discussing concepts related to Integrations.
theme: jekyll-theme-cayman
